var RELANG = {};
RELANG['ru'] = {
	html: 'HTML',
	video: 'Видео',
	image: 'Изображение',
	table: 'Таблица',
	link: 'Ссылка',
	link_insert: 'Вставить ссылку ...',
	unlink: 'Удалить ссылку',
	formatting: 'Форматирование',
	paragraph: 'Обычный текст',
	quote: 'Цитата',
	code: 'Код',
	header1: 'Заголовок 1',
	header2: 'Заголовок 2',
	header3: 'Заголовок 3',
	header4: 'Заголовок 4',		
	header5: 'Заголовок 5',
	header6: 'Заголовок 6',		
	bold:  'Полужирный',
	italic: 'Наклонный',
	fontcolor: 'Цвет текста',
	backcolor: 'Заливка текста',
	unorderedlist: 'Обычный список',
	orderedlist: 'Нумерованный список',	
	outdent: 'Уменьшить отступ',
	indent: 'Увеличить отступ',
	cancel: 'Отменить',	
	insert: 'Вставить',
	save: 'Сохранить',	
	_delete: 'Удалить',
	insert_table: 'Вставить таблицу',
	insert_row_above: 'Добавить строку сверху',
	insert_row_below: 'Добавить строку снизу',
	insert_column_left: 'Добавить столбец слева',
	insert_column_right: 'Добавить столбец справа',									
	delete_column: 'Удалить столбец',									
	delete_row: 'Удалить строку',									
	delete_table: 'Удалить таблицу',
	rows: 'Строки',
	columns: 'Столбцы',	
	add_head: 'Добавить заголовок',
	delete_head: 'Удалить заголовок',	
	title: 'Подсказка',
	/*ZharinaViktor image_position: 'Обтекание текстом',*/
	image_position: 'Выравнивание',
	/*ZharinaViktor*/
	none: 'Нет',	
	left: 'Cлева',
	right: 'Cправа',
	image_web_link: 'Cсылка на изображение',
	text: 'Текст',
	mailto: 'Эл. почта',
	web: 'URL',
	video_html_code: 'Код видео ролика',
	file: 'Файл',
	upload: 'Загрузить',
	download: 'Скачать',
	choose: 'Выбрать',
	or_choose: 'Или выберите',
	drop_file_here: 'Перетащите файл сюда',
	align_left:	'По левому краю',	
	align_center: 'По центру',
	align_right: 'По правому краю',
	align_justify: 'Выровнять текст по ширине',
	horizontalrule: 'Горизонтальная линейка',
	fullscreen: 'Во весь экран',
	deleted: 'Зачеркнутый',
	anchor: 'Якорь',
	spoiler: 'Cпойлер',
	spoiler_header: 'Заголовок спойлера',
	spoiler_text: 'Текст спойлера',
	smiles_text: 'Добавить смайл',
	smiles_text: 'Смайлы',
	ls_user_text: 'Введите имя юзера',
	underline: 'Подчеркнутый',
	others: 'Еще',
	bluepost: 'BluePost',
	hide: 'Скрыть',
	center: 'Центр',
	err_filename_not_set:' Ошибка(1) загрузки файла. Имя файла не задано.',
	err_type_restricted:'Ошибка(2) загрузки файла. Данный тип файла запрещен для загрузки.',
	err_file_is_not_image:'Ошибка(3) загрузки файла. Файл не является изображением, для загрузки используйте кнопку "Файл".',
	err_file_is_too_large:'Ошибка(4) загрузки файла. Файл слишком большого размера.',
	err_create_image_dir:'Ошибка(5) создания дирректории для изображений.',
	err_filecopy_error:'Ошибка(6) копирования файла в дирректорию для изображений.',
	err_file_is_image:'Ошибка(7) загрузки файла. Файл является изображением, для загрузки используйте кнопку "Изображение".',
	err_url_struct_is_not_set:'Ошибка(8) загрузки файла. Структура url не задана. Задайте структуру url.',
    link_new_tab: 'Открыть ссылку в новом окне'
};


